version: '3.1'

services:
    web_client:
        build:
          context: ./
          dockerfile: ./Applications.WebClient/Dockerfile
        image: pong/web_client:0.1
        container_name: web_client
        hostname: web_client
        ports:
          - 5000:80
        networks:
          - pong_network
        volumes:
          - "./logs:/Logs"
          - "./resources:/resources"

        depends_on:
          db:
            condition: service_healthy
      
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        networks:
          - pong_network
          

networks:
  pong_network: